# -*- coding: utf-8 -*-

- !ruby/object:CardData
  name: 魚
  type: :resource
  unlock_level: 0

- !ruby/object:CardData
  name: 貝  
  type: :resource
  unlock_level: 10

- !ruby/object:CardData
  name: 蟹
  type: :resource
  unlock_level: 30

- !ruby/object:CardData
  name: 小麦
  type: :resource
  unlock_level: 18

- !ruby/object:CardData
  name: 米
  type: :resource
  unlock_level: 18

- !ruby/object:CardData
  name: とうもろこし
  type: :resource
  unlock_level: 18
